plugins { id 'com.android.application' }

android {
    namespace 'com.mikesmathcoach'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mikesmathcoach'
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName '1.6.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}