plugins { id 'com.android.application' }

def stableTestKeystore = rootProject.file('ci/mikes-math-test.keystore')

android {
    namespace 'com.mikesmathcoach'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mikesmathcoach.test'
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName '1.6.5-test'
    }

    signingConfigs {
        stableTest {
            if (stableTestKeystore.exists()) {
                storeFile stableTestKeystore
                storePassword 'mikesmathdebug'
                storeType 'JKS'
                keyAlias 'mikesmathdebug'
                keyPassword 'mikesmathdebug'
            }
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableTest
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}